/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Praktikum_29062026;

/**
 *
 * @author Lenovo
 */
public class FormMinuman extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormMinuman.class.getName());

    /**
     * Creates new form FormMinuman
     */
    private FormUtama utama;
    public FormMinuman() {
        initComponents();
    }

    public FormMinuman(FormUtama utama) {
        this.utama = utama;
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJudul = new javax.swing.JLabel();
        ckbSoda = new javax.swing.JCheckBox();
        ckbJeruk = new javax.swing.JCheckBox();
        ckbKeljer = new javax.swing.JCheckBox();
        ckbKelapa = new javax.swing.JCheckBox();
        txtSoda = new javax.swing.JTextField();
        txtJeruk = new javax.swing.JTextField();
        txtKeljer = new javax.swing.JTextField();
        txtKelapa = new javax.swing.JTextField();
        cbSoda = new javax.swing.JComboBox<>();
        cbJeruk = new javax.swing.JComboBox<>();
        cbKeljer = new javax.swing.JComboBox<>();
        cbKelapa = new javax.swing.JComboBox<>();
        txtTotalSoda = new javax.swing.JTextField();
        txtTotalJeruk = new javax.swing.JTextField();
        txtTotalKeljer = new javax.swing.JTextField();
        txtTotalKelapa = new javax.swing.JTextField();
        btnTotal = new javax.swing.JButton();
        txtTotal = new javax.swing.JTextField();
        btnKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblJudul.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        lblJudul.setText("PILIHAN MENU MINUMAN");

        ckbSoda.setText("Soda");
        ckbSoda.addActionListener(this::ckbSodaActionPerformed);

        ckbJeruk.setText("Es Jeruk");
        ckbJeruk.addActionListener(this::ckbJerukActionPerformed);

        ckbKeljer.setText("Kelapa Jeruk");
        ckbKeljer.addActionListener(this::ckbKeljerActionPerformed);

        ckbKelapa.setText("Es Kelapa");
        ckbKelapa.addActionListener(this::ckbKelapaActionPerformed);

        txtSoda.setText("0");
        txtSoda.addActionListener(this::txtSodaActionPerformed);

        txtJeruk.setText("0");

        txtKeljer.setText("0");

        txtKelapa.setText("0");

        cbSoda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbSoda.addActionListener(this::cbSodaActionPerformed);

        cbJeruk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        cbJeruk.addActionListener(this::cbJerukActionPerformed);

        cbKeljer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbKeljer.addActionListener(this::cbKeljerActionPerformed);

        cbKelapa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbKelapa.addActionListener(this::cbKelapaActionPerformed);

        txtTotalSoda.setText("0");

        txtTotalJeruk.setText("0");

        txtTotalKeljer.setText("0");

        txtTotalKelapa.setText("0");

        btnTotal.setText("Total Harga");
        btnTotal.addActionListener(this::btnTotalActionPerformed);

        txtTotal.setText("0");

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(this::btnKeluarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(lblJudul))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ckbKelapa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtKelapa, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ckbKeljer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtKeljer, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(ckbJeruk)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtJeruk, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(ckbSoda)
                                .addGap(80, 80, 80)
                                .addComponent(txtSoda, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cbSoda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbJeruk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbKeljer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbKelapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(88, 88, 88)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtTotalSoda, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTotalJeruk, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTotalKeljer, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTotalKelapa, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(btnKeluar)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblJudul)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbSoda)
                    .addComponent(txtSoda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSoda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalSoda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbJeruk)
                    .addComponent(txtJeruk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbJeruk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalJeruk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbKeljer)
                    .addComponent(txtKeljer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbKeljer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalKeljer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbKelapa)
                    .addComponent(txtKelapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbKelapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalKelapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTotal)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(btnKeluar)
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbSodaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSodaActionPerformed
        int jumlah = (int)cbSoda.getSelectedIndex();
        double harga = Double.parseDouble(txtSoda.getText());
        double total = jumlah*harga;
        txtTotalSoda.setText(Double.toString(total));
    }//GEN-LAST:event_cbSodaActionPerformed

    private void txtSodaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSodaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSodaActionPerformed

    private void ckbSodaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbSodaActionPerformed
        txtSoda.setText("15000");
    }//GEN-LAST:event_ckbSodaActionPerformed

    private void ckbJerukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbJerukActionPerformed
        txtJeruk.setText("12000");
    }//GEN-LAST:event_ckbJerukActionPerformed

    private void ckbKeljerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbKeljerActionPerformed
        txtKeljer.setText("20000");
    }//GEN-LAST:event_ckbKeljerActionPerformed

    private void ckbKelapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbKelapaActionPerformed
        txtKelapa.setText("10000");
    }//GEN-LAST:event_ckbKelapaActionPerformed

    private void cbJerukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJerukActionPerformed
        int jumlah = (int)cbJeruk.getSelectedIndex();
        double harga = Double.parseDouble(txtJeruk.getText());
        double total = jumlah*harga;
        txtTotalJeruk.setText(Double.toString(total));
    }//GEN-LAST:event_cbJerukActionPerformed

    private void cbKeljerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKeljerActionPerformed
        int jumlah = (int)cbKeljer.getSelectedIndex();
        double harga = Double.parseDouble(txtKeljer.getText());
        double total = jumlah*harga;
        txtTotalKeljer.setText(Double.toString(total));
    }//GEN-LAST:event_cbKeljerActionPerformed

    private void cbKelapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKelapaActionPerformed
        int jumlah = (int)cbKelapa.getSelectedIndex();
        double harga = Double.parseDouble(txtKelapa.getText());
        double total = jumlah*harga;
        txtTotalKelapa.setText(Double.toString(total));
    }//GEN-LAST:event_cbKelapaActionPerformed

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
        double a = Double.parseDouble(txtTotalSoda.getText());
        double b = Double.parseDouble(txtTotalJeruk.getText());
        double c = Double.parseDouble(txtTotalKeljer.getText());
        double d = Double.parseDouble(txtTotalKelapa.getText());
        double total = a+b+c+d;
        txtTotal.setText(Double.toString(total));
    }//GEN-LAST:event_btnTotalActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        String total = txtTotal.getText();
        utama.setTotalMinuman(total);
        this.dispose();//SETELAH DIPINDAH FORM HILANG
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormMinuman().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnTotal;
    private javax.swing.JComboBox<String> cbJeruk;
    private javax.swing.JComboBox<String> cbKelapa;
    private javax.swing.JComboBox<String> cbKeljer;
    private javax.swing.JComboBox<String> cbSoda;
    private javax.swing.JCheckBox ckbJeruk;
    private javax.swing.JCheckBox ckbKelapa;
    private javax.swing.JCheckBox ckbKeljer;
    private javax.swing.JCheckBox ckbSoda;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JTextField txtJeruk;
    private javax.swing.JTextField txtKelapa;
    private javax.swing.JTextField txtKeljer;
    private javax.swing.JTextField txtSoda;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTotalJeruk;
    private javax.swing.JTextField txtTotalKelapa;
    private javax.swing.JTextField txtTotalKeljer;
    private javax.swing.JTextField txtTotalSoda;
    // End of variables declaration//GEN-END:variables
}
