/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Praktikum_29062026;

/**
 *
 * @author Lenovo
 */
public class FormMakanan extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormMakanan.class.getName());

    /**
     * Creates new form FormMakanan
     */
   

    
    private FormUtama utama;
    
    public FormMakanan() {
        initComponents();
    }
     public FormMakanan(FormUtama utama) {
        this.utama = utama;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ckbNasgor = new javax.swing.JCheckBox();
        ckbMigor = new javax.swing.JCheckBox();
        ckbMire = new javax.swing.JCheckBox();
        txtNasgor = new javax.swing.JTextField();
        txtMigor = new javax.swing.JTextField();
        txtMire = new javax.swing.JTextField();
        cbNasgor = new javax.swing.JComboBox<>();
        cbMigor = new javax.swing.JComboBox<>();
        cbMire = new javax.swing.JComboBox<>();
        txtTotalNasgor = new javax.swing.JTextField();
        txtTotalMigor = new javax.swing.JTextField();
        txtTotalMire = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        btnKeluar = new javax.swing.JButton();
        btnTotal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel1.setText("PILIHAN MENU MAKANAN");

        ckbNasgor.setText("Nasi Goreng");
        ckbNasgor.addActionListener(this::ckbNasgorActionPerformed);

        ckbMigor.setText("Mie Goreng");
        ckbMigor.addActionListener(this::ckbMigorActionPerformed);

        ckbMire.setText("Mie Rebus");
        ckbMire.addActionListener(this::ckbMireActionPerformed);

        txtNasgor.setText("0");

        txtMigor.setText("0");

        txtMire.setText("0");

        cbNasgor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        cbNasgor.addActionListener(this::cbNasgorActionPerformed);

        cbMigor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbMigor.addActionListener(this::cbMigorActionPerformed);

        cbMire.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbMire.addActionListener(this::cbMireActionPerformed);

        txtTotalNasgor.setText("0");

        txtTotalMigor.setText("0");

        txtTotalMire.setText("0");

        txtTotal.setText("0");

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(this::btnKeluarActionPerformed);

        btnTotal.setText("Total Harga");
        btnTotal.addActionListener(this::btnTotalActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(178, 178, 178))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ckbNasgor)
                            .addComponent(ckbMire, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ckbMigor, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNasgor, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addComponent(cbNasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(txtTotalNasgor, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnTotal)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtMigor, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtMire, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(68, 68, 68)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(cbMigor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbMire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTotalMigor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtTotalMire, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(btnKeluar)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbNasgor)
                    .addComponent(txtNasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbNasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalNasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbMigor)
                    .addComponent(txtMigor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMigor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalMigor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbMire)
                    .addComponent(txtMire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalMire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(btnKeluar)
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ckbMigorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbMigorActionPerformed
        txtMigor.setText("10000");
    }//GEN-LAST:event_ckbMigorActionPerformed

    private void ckbNasgorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbNasgorActionPerformed
        txtNasgor.setText("15000");
    }//GEN-LAST:event_ckbNasgorActionPerformed

    private void ckbMireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbMireActionPerformed
        txtMire.setText("10000");
    }//GEN-LAST:event_ckbMireActionPerformed

    private void cbNasgorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNasgorActionPerformed
        int jumlah = (int)cbNasgor.getSelectedIndex();
        double harga = Double.parseDouble(txtNasgor.getText());
        double total = jumlah*harga;
        txtTotalNasgor.setText(Double.toString(total));
    }//GEN-LAST:event_cbNasgorActionPerformed

    private void cbMigorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMigorActionPerformed
        int jumlah = (int)cbMigor.getSelectedIndex();
        double harga = Double.parseDouble(txtMigor.getText());
        double total = jumlah*harga;
        txtTotalMigor.setText(Double.toString(total));
    }//GEN-LAST:event_cbMigorActionPerformed

    private void cbMireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMireActionPerformed
        int jumlah = (int)cbMire.getSelectedIndex();
        double harga = Double.parseDouble(txtMire.getText());
        double total = jumlah*harga;
        txtTotalMire.setText(Double.toString(total));
    }//GEN-LAST:event_cbMireActionPerformed

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
        double a = Double.parseDouble(txtTotalNasgor.getText());
        double b = Double.parseDouble(txtTotalMigor.getText());
        double c = Double.parseDouble(txtTotalMire.getText());
        double total = a+b+c;
        txtTotal.setText(Double.toString(total));
    }//GEN-LAST:event_btnTotalActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        String total = txtTotal.getText();
        utama.setTotalMakanan(total);
        this.dispose();//SETELAH DIPINDAH FORM HILANG
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormMakanan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnTotal;
    private javax.swing.JComboBox<String> cbMigor;
    private javax.swing.JComboBox<String> cbMire;
    private javax.swing.JComboBox<String> cbNasgor;
    private javax.swing.JCheckBox ckbMigor;
    private javax.swing.JCheckBox ckbMire;
    private javax.swing.JCheckBox ckbNasgor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtMigor;
    private javax.swing.JTextField txtMire;
    private javax.swing.JTextField txtNasgor;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTotalMigor;
    private javax.swing.JTextField txtTotalMire;
    private javax.swing.JTextField txtTotalNasgor;
    // End of variables declaration//GEN-END:variables
}
